FullIdentity/Controllers/MemberController.cs
using FullIdentity.Enums;
using FullIdentity.Models;
using Mapster;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace FullIdentity.Controllers
{
    [Authorize]
    public class MemberController : BaseController
    {

        public MemberController(UserManager<AppUser> userManager,SignInManager<AppUser> signInManager):base(userManager,signInManager)
        {
            
        }


        public IActionResult Index()
        {
            AppUser user = CurrentUser;
            MemberViewModel memberViewModel = user.Adapt<MemberViewModel>();
            return View(memberViewModel);
        }

        [HttpGet]
        public IActionResult ChangePassword()
        {
            return View();
        }

        [HttpPost]
        public IActionResult ChangePassword(ChangePasswordViewModel changePasswordViewModel)
        {
            AppUser user = CurrentUser;

            if (changePasswordViewModel.OldPassword != null)
            {
                bool exist = _userManager.CheckPasswordAsync(user, changePasswordViewModel.OldPassword).Result;

                if (exist)
                {

                    if (changePasswordViewModel.NewPassword == changePasswordViewModel.NewPasswordConfirm)
                    {
                        IdentityResult result = _userManager.ChangePasswordAsync(user, changePasswordViewModel.OldPassword, changePasswordViewModel.NewPassword).Result;

                        if (result.Succeeded)
                        {
                            _userManager.UpdateSecurityStampAsync(user);

                            /*_signInManager.SignOutAsync();
                            _signInManager.PasswordSignInAsync(user,changePasswordViewModel.NewPassword,true,false);*/ //bulari versek parolu deyisdikden sonra 30 dqhye bizi logine atmaz ozu cixis edib giris edecek

                            ViewBag.success = "true";
                        }
                        else
                        {
                            AddModelError(result);
                        }
                    }
                    else
                    {
                        ModelState.AddModelError("", "Sifreler eyni deyil");
                    }

                }
                else
                {
                    ModelState.AddModelError("", "Kohne sifreniz duzgun deyil");
                }
            }
            else
            {
                ModelState.AddModelError("","Fieldlar bos ola bilmez");
            }
            
            return View(changePasswordViewModel);
        }

        [HttpGet]
        public IActionResult EditUser()
        {
            AppUser user = CurrentUser;
            MemberViewModel editUserViewModel = user.Adapt<MemberViewModel>();
            ViewBag.Gender = new SelectList(Enum.GetNames(typeof(Gender)));
            return View(editUserViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> EditUser(MemberViewModel editUserViewModel,IFormFile userPicture)
        {

            ViewBag.Gender = new SelectList(Enum.GetNames(typeof(Gender)));

            if (ModelState.IsValid)
            {
                AppUser user = CurrentUser;

                if (userPicture != null && userPicture.Length > 0)
                {
                    var fileName = Guid.NewGuid() + Path.GetExtension(userPicture.FileName);

                    var path = Path.Combine(Directory.GetCurrentDirectory(),"wwwroot/userImage",fileName);

                    using (var stream  = new FileStream(path,FileMode.Create))
                    {
                        await userPicture.CopyToAsync(stream);

                        user.Picture = "/userImage/" + fileName;
                    }
                }

                user.UserName = editUserViewModel.UserName;
                user.Email = editUserViewModel.Email;
                user.PhoneNumber = editUserViewModel.PhoneNumber;
                user.City = editUserViewModel.City;
                user.BirthDate = editUserViewModel.BirthDate;
                user.Gender = (int)editUserViewModel.Gender;

                IdentityResult result = await _userManager.UpdateAsync(user);

                if (result.Succeeded)
                {
                    await _userManager.UpdateSecurityStampAsync(user);

                    ViewBag.success = "true";
                }
                else
                {
                    AddModelError(result);
                }
            }
            
            return View(editUserViewModel);
        }

        public IActionResult LogOut()
        {
            _signInManager.SignOutAsync();
            return RedirectToAction("Index","Home");
        }

        [Authorize(Roles = "Editor,Admin")]
        public IActionResult Editor()
        {
            return View();
        }

        [Authorize(Roles = "Manager,Admin")]
        public IActionResult Manager()
        {
            return View();
        }

        public IActionResult MyClaims()
        {
            
            return View(User.Claims.ToList());
        }

        [Authorize(Policy = "BakuPolicy")]
        public IActionResult Baku()
        {
            return View();
        }

        [Authorize(Policy = "ViolencePolicy")]
        public IActionResult Violence()
        {
            return View();
        }


        public async Task<IActionResult> ExchangeRedirect()
        {
            bool result = User.HasClaim(x => x.Type == "ExpireDateExchange");

            if (!result)
            {
                Claim claim = new Claim("ExpireDateExchange",DateTime.Now.AddDays(30).Date.ToShortDateString(),ClaimValueTypes.String,"Internal");

                await _userManager.AddClaimAsync(CurrentUser,claim);
                await _signInManager.SignOutAsync();
                await _signInManager.SignInAsync(CurrentUser,true);
            }

            return RedirectToAction("Exchange");
        }

        [Authorize(Policy = "ExchangePolicy")]
        public IActionResult Exchange()
        {
            return View();
        }
    }
}

FullIdentity/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FullIdentity</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FullIdentity</a>
              
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin Main Page</a>
                        </li>
                
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container" style="margin-top:10px;">
        <div class="row">
            <div class="col-md-8">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
            <div class="col-md-4">
                <h3>Menu</h3>
                <a class="btn btn-danger btn-block" asp-area="" asp-controller="Admin" asp-action="Users">Users</a>
                <a class="btn btn-danger btn-block" asp-area="" asp-controller="Admin" asp-action="Roles">Roles</a>
                <a class="btn btn-danger btn-block" asp-area="" asp-controller="Member" asp-action="LogOut">Cixis</a>
            </div>
        </div>
   
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - FullIdentity - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

FullIdentity/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FullIdentity</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FullIdentity</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="SignUp">Qeydiyyat</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Giris</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - FullIdentity - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

FullIdentity/Views/Shared/_MemberLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FullIdentity</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FullIdentity</a>
              
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Member" asp-action="Index">User Main Page</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Member" asp-action="Baku">Baku Page</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Member" asp-action="Violence">Violence Page</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Member" asp-action="ExchangeRedirect">Exchange Page</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container" style="margin-top:10px;">
        <div class="row">
            <div class="col-md-8">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
            <div class="col-md-4">
                <h3>Menu</h3>
                <a class="btn btn-info btn-block" asp-area="" asp-controller="Admin" asp-action="Index">Admin Page</a>
                <a class="btn btn-info btn-block" asp-area="" asp-controller="Member" asp-action="MyClaims">My Claims</a>
                <a class="btn btn-info btn-block" asp-area="" asp-controller="Member" asp-action="ChangePassword">Sifreni deyis</a>
                <a class="btn btn-info btn-block" asp-area="" asp-controller="Member" asp-action="EditUser">Melumatlari yenile</a>
                <a class="btn btn-info btn-block" asp-area="" asp-controller="Member" asp-action="LogOut">Cixis</a>
            </div>
        </div>
   
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - FullIdentity - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>